module.exports = [
    { 'key': undefined, 'val': ''},
    { 'key': 1, 'val': 'Alabama'},
    { 'key': 2, 'val': 'Alaska'},
    { 'key': 4, 'val': 'Arizona'},
    { 'key': 5, 'val': 'Arkansas'},
    { 'key': 6, 'val': 'California'},
    { 'key': 8, 'val': 'Colorado'},
    { 'key': 9, 'val': 'Connecticut'},
    { 'key': 10, 'val': 'Delaware'},
    { 'key': 11, 'val': 'Dist. of Col.'},
    { 'key': 12, 'val': 'Florida'},
    { 'key': 13, 'val': 'Georgia'},
    { 'key': 15, 'val': 'Hawaii'},
    { 'key': 16, 'val': 'Idaho'},
    { 'key': 17, 'val': 'Illinois'},
    { 'key': 18, 'val': 'Indiana'},
    { 'key': 19, 'val': 'Iowa'},
    { 'key': 20, 'val': 'Kansas'},
    { 'key': 21, 'val': 'Kentucky'},
    { 'key': 22, 'val': 'Louisiana'},
    { 'key': 23, 'val': 'Maine'},
    { 'key': 24, 'val': 'Maryland'},
    { 'key': 25, 'val': 'Massachusetts'},
    { 'key': 26, 'val': 'Michigan'},
    { 'key': 27, 'val': 'Minnesota'},
    { 'key': 28, 'val': 'Mississippi'},
    { 'key': 29, 'val': 'Missouri'},
    { 'key': 30, 'val': 'Montana'},
    { 'key': 31, 'val': 'Nebraska'},
    { 'key': 32, 'val': 'Nevada'},
    { 'key': 33, 'val': 'New Hampshire'},
    { 'key': 34, 'val': 'New Jersey'},
    { 'key': 35, 'val': 'New Mexico'},
    { 'key': 36, 'val': 'New York'},
    { 'key': 37, 'val': 'North Carolina'},
    { 'key': 38, 'val': 'North Dakota'},
    { 'key': 39, 'val': 'Ohio'},
    { 'key': 40, 'val': 'Oklahoma'},
    { 'key': 41, 'val': 'Oregon'},
    { 'key': 42, 'val': 'Pennsylvania'},
    { 'key': 44, 'val': 'Rhode Island'},
    { 'key': 45, 'val': 'South Carolina'},
    { 'key': 46, 'val': 'South Dakota'},
    { 'key': 47, 'val': 'Tennessee'},
    { 'key': 48, 'val': 'Texas'},
    { 'key': 49, 'val': 'Utah'},
    { 'key': 50, 'val': 'Vermont'},
    { 'key': 51, 'val': 'Virginia'},
    { 'key': 53, 'val': 'Washington'},
    { 'key': 54, 'val': 'West Virginia'},
    { 'key': 55, 'val': 'Wisconsin'},
    { 'key': 56, 'val': 'Wyoming'}
]