module.exports = [
    { 'key': undefined, 'val': ''},
    { 'key': 1, 'val': 'Clear'},
    { 'key': 0, 'val': 'No Additional Atmospheric Conditions'},
    { 'key': 2, 'val': 'Rain'},
    { 'key': 3, 'val': 'Sleet, Hail'},
    { 'key': 4, 'val': 'Snow'},
    { 'key': 5, 'val': 'Fog, Smog, Smoke'},
    { 'key': 6, 'val': 'Severe Crosswinds'},
    { 'key': 7, 'val': 'Blowing Sand, Soil, Dirt'},
    { 'key': 8, 'val': 'Other'},
    { 'key': 10, 'val': 'Cloudy'},
    { 'key': 11, 'val': 'Blowing Snow'},
    { 'key': 12, 'val': 'Freezing Rain or Drizzle'},
    { 'key': 98, 'val': 'Not Reported'},
    { 'key': 99, 'val': 'Unknown'},
]